upkeep: add minimal unit testing
RMI-PACTA/pacta.portfolio.report pull request #64
Opened 2024-04-16 09:29 UTC by jdhoffa

This adds some minimal unit tests to the low-hanging fruit. 

Obviously `create_interactive_report` is the real elephant in the room here, but I want to tackle that in a separate PR/ issue (see #63)

<img width="391" alt="Screenshot 2024-04-16 at 11 29 45" src="https://github.com/RMI-PACTA/pacta.portfolio.report/assets/8741309/93d393f8-5f2a-442d-af2c-03db46f89fa0">

Closes #30

2024-04-16 09:38 UTC, cjyetman requested changes

2024-04-16 09:38 UTC, cjyetman commented on tests/testthat/test-select_report_template.R
> +test_that("with fake args, returnsexpected string structure", {
```suggestion
test_that("with fake args, returns expected string structure", {
```

2024-04-16 10:26 UTC, cjyetman approved these changes

2024-04-18 13:31 UTC, MonikaFu approved these changes
LGTM

2024-04-18 13:32 UTC, merged